<!DOCTYPE HTML>
<html>
<head>
    <title><?php echo $title?></title>
    <meta charset="utf-8">
    <meta name="renderer" content="webkit|ie-comp|ie-stand">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
    <link rel="Bookmark" href="/favicon.ico" >
    <link rel="Shortcut Icon" href="/favicon.ico" />
    <!--[if lt IE 9]>
    <script type="text/javascript" src="/admin_assert/lib/html5shiv.js"></script>
    <script type="text/javascript" src="/admin_assert/lib/respond.min.js"></script>
    <![endif]-->
    <link rel="stylesheet" type="text/css" href="/admin_assert/static/h-ui/css/H-ui.min.css" />
    <link rel="stylesheet" type="text/css" href="/admin_assert/static/h-ui.admin/css/H-ui.admin.css" />
    <link rel="stylesheet" type="text/css" href="/admin_assert/lib/Hui-iconfont/1.0.8/iconfont.css" />
    <link rel="stylesheet" type="text/css" href="/admin_assert/static/h-ui.admin/skin/default/skin.css" id="skin" />
    <link rel="stylesheet" type="text/css" href="/admin_assert/static/h-ui.admin/css/style.css" />
    <!--[if IE 6]>
    <script type="text/javascript" src="/admin_assert/lib/DD_belatedPNG_0.0.8a-min.js" ></script>
    <![endif]-->
    <?php $this->assets->outputCss() ?>
</head>
<body>
<?php echo $this->getContent(); ?>
</body>
</html>
